---
development:
  cloudinary_cloud_name: sarop-bajra
  cloudinary_api_key: '883945247258735'
  cloudinary_api_secret: PktUqXjqoOg8s4nsjDPiFp7kWRI
test:
  cloudinary_cloud_name: sarop-bajra
  cloudinary_api_key: '883945247258735'
  cloudinary_api_secret: PktUqXjqoOg8s4nsjDPiFp7kWRI
production:
  cloudinary_cloud_name: sarop-bajra
  cloudinary_api_key: '883945247258735'
  cloudinary_api_secret: PktUqXjqoOg8s4nsjDPiFp7kWRI
